# Generated by Django 5.0.6 on 2024-08-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_patient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Email',
            new_name='email',
        ),
    ]
