# Generated by Django 3.0.5 on 2024-07-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_auto_20240726_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='Email',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
