# Generated by Django 3.0.5 on 2024-07-27 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_donor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='Email',
        ),
    ]
