# Generated by Django 5.0.8 on 2024-08-08 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_alter_blooddonate_id_alter_donor_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='donor',
        ),
    ]
