# Generated by Django 5.0.8 on 2024-08-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0010_alter_donor_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table=None,
        ),
    ]
