# Generated by Django 5.0.6 on 2024-08-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_alter_blooddonate_id_alter_donor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Email',
            new_name='email',
        ),
    ]
