# Generated by Django 3.0.5 on 2024-07-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0007_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='address',
            new_name='district',
        ),
    ]
