# Generated by Django 5.0.6 on 2024-08-18 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0010_alter_bloodrequest_id_alter_stock_id_alter_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email',
            new_name='email',
        ),
    ]
